# Generated by Django 6.0.7 on 2026-08-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Zona de Envío', 'verbose_name_plural': 'Zonas de Envío'},
        ),
        migrations.AlterModelOptions(
            name='giftbox',
            options={'ordering': ['display_order', '-featured', 'name'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Ocasión', 'verbose_name_plural': 'Ocasiones'},
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='estimated_days',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tiempo estimado'),
        ),
        migrations.AddField(
            model_name='giftbox',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftbox',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='giftbox',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='giftbox',
            name='sku',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='giftbox',
            name='unlimited_stock',
            field=models.BooleanField(default=False, verbose_name='Stock ilimitado'),
        ),
        migrations.AddField(
            model_name='giftbox',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso en Kg', max_digits=6),
        ),
        migrations.AddField(
            model_name='giftboxitem',
            name='optional',
            field=models.BooleanField(default=False, verbose_name='Producto opcional'),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Envío a domicilio'), ('pickup', 'Retiro por el local')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='preference_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dedication',
            field=models.TextField(blank=True, default='', verbose_name='Dedicatoria'),
        ),
        migrations.AlterField(
            model_name='giftbox',
            name='personalized',
            field=models.BooleanField(default=False, verbose_name='Permite dedicatoria'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.deliveryzone'),
        ),
    ]
