# Generated by Django 6.0.7 on 2026-08-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_deliveryzone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='giftbox',
            name='image',
            field=models.ImageField(max_length=255, upload_to='gift-boxes/'),
        ),
        migrations.AlterField(
            model_name='giftboximage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='gift-boxes/gallery/'),
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='gift-items/'),
        ),
    ]
