# Generated by Django 6.0.7 on 2026-08-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_image_alter_giftbox_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftitem',
            name='image',
        ),
    ]
