# Generated by Django 6.0.7 on 2026-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_giftitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text="Se muestra borrosa con un cartel de 'Próximamente' y no se puede abrir todavía.", verbose_name='Próximamente'),
        ),
    ]
