"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de config/.env (API keys, etc.) como variables de entorno.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En local, si SECRET_KEY no está en el .env, usa esta de desarrollo
# (no importa que sea pública). En producción SIEMPRE hay que definir
# SECRET_KEY en las variables de entorno del hosting con una propia.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-_z)-lar^ha+^fz(9f2*2d%tmmj-*=1n-cloo-3x2^g7-=0w(gz',
)

# DEBUG=True solo en local. En producción, definir DEBUG=False (o directamente
# no definir la variable) en el panel del hosting.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Dominios permitidos, separados por coma (ej: "regalboxx.onrender.com,midominio.com").
# En local no hace falta configurarlo.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]

# Necesario en Django 4+ para aceptar POSTs (login admin, formularios) detrás
# de HTTPS en el hosting. Mismo formato que ALLOWED_HOSTS pero con esquema.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

if not DEBUG:
    # Buenas prácticas de seguridad para producción (HTTPS real).
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# En local, sin DATABASE_URL en el .env, sigue usando SQLite como siempre.
# En producción, DATABASE_URL apunta a Postgres (ej: la connection string
# que da Neon), y dj_database_url la traduce a lo que espera Django.

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary: si hay credenciales en el .env, las imágenes que suban desde
# el admin (categorías, boxes, productos) se guardan ahí en vez del disco
# local — necesario en hostings con disco efímero (se borra en cada
# redeploy). En local, sin CLOUDINARY_URL, sigue usando el disco normal.
#
# Se genera gratis en https://cloudinary.com -> Dashboard -> "API Environment
# variable" (el CLOUDINARY_URL completo, con el formato
# cloudinary://<api_key>:<api_secret>@<cloud_name>).

CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')

STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if CLOUDINARY_URL
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        # Storage simple (sin pre-comprimir en collectstatic — eso rompía
        # con archivos internos del admin de Django/select2). El
        # middleware de whitenoise igual comprime al servir cada request,
        # solo que al vuelo en vez de precalculado.
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Compat: django-cloudinary-storage 0.3.0 todavía lee STATICFILES_STORAGE/
# DEFAULT_FILE_STORAGE directamente en vez del STORAGES nuevo de Django.
STATICFILES_STORAGE = STORAGES['staticfiles']['BACKEND']
DEFAULT_FILE_STORAGE = STORAGES['default']['BACKEND']


# ==========================================================
# REGALBOXX
# ==========================================================

# Número de WhatsApp de la tienda (con código de país, sin "+", sin espacios).
# Formato Argentina para wa.me: 54 9 <código de área> <número>.
WHATSAPP_NUMBER = '5492216816529'

# Los pedidos se numeran como RB-000XXX = id del pedido + este offset,
# para que la numeración no arranque en "Pedido #1".
ORDER_CODE_OFFSET = 510


# ==========================================================
# GIFT FINDER (IA)
# ==========================================================

# Se carga desde .env — ver .env.example. Vacía = el Gift Finder
# responde con un mensaje de "todavía no está disponible" en vez
# de romper.
# Se genera gratis (sin tarjeta) en https://console.groq.com -> API Keys.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

# Modelo de Groq con soporte de tool-use, dentro de la capa gratuita.
# Se probó bajar al modelo chico (8B) para tener más cuota diaria, pero
# usa mal las herramientas (a veces escribe el llamado a la función como
# texto plano en vez de invocarla de verdad), lo que rompe la
# recomendación. El 70B es mucho más confiable con tool-calling — la
# cuota diaria (100k tokens) alcanza de sobra para uso real de la
# tienda, lo que la agotó hoy fue el testing intensivo, no tráfico real.
# Si Groq lo discontinúa, revisar el listado vigente en
# https://console.groq.com/docs/models y reemplazar acá.
GIFT_FINDER_MODEL = 'llama-3.3-70b-versatile'

GIFT_FINDER_PERSONA_NAME = 'Regi'

# Tope de mensajes del usuario por conversación, para controlar costo
# y evitar loops largos. Al llegar al tope, se invita a seguir por WhatsApp.
GIFT_FINDER_MAX_USER_TURNS = 10
